### ISSUE TITLE
The copyright is outdated

### ISSUE THREAD

**Issue by kuraga** [projg2/installkernel-gentoo#12]
The last year is 2009:

https://github.com/projg2/installkernel-gentoo/blob/e9b9c694a20df9cac1469d4145434716d4235551/installkernel#L3-L7

The `/hooks/**/*` files don't have a copyright at all.

Also, should we replace the Debian mention?

https://github.com/projg2/installkernel-gentoo/blob/e9b9c694a20df9cac1469d4145434716d4235551/installkernel#L9-L14

**Comment by AndrewAmmerlaan** [comment]
Fixed!
