### ISSUE TITLE
Adding app-emulation/virt-firmware as a dependency

### ISSUE THREAD

**Issue by Biosias** [projg2/installkernel-gentoo#22]
Hello again,

would it be possible to make `app-emulation/virt-firmware` dependency of installkernel if use flag efistub is chosen? 
Or is there some reason it was not done this way?

**Comment by AndrewAmmerlaan** [comment]
This is already the case in version 29:
```
	efistub? (
		>=app-emulation/virt-firmware-24.2_p20240315-r2
		|| (
			sys-apps/systemd[boot(-)]
			sys-apps/systemd-utils[boot(-)]
		)
	)
```
