### ISSUE TITLE
[no systemd] [efistub] root kernel flag uses currently running system instead of mounted root partition

### ISSUE THREAD

**Issue by SpomJ** [projg2/installkernel-gentoo#27]
When installing a kernel through chroot, kernel `root=` sets to currently running system, while it should set for filesystem mounted as /.

<details>

<summary>Example</summary>

Mounts:

```
i-use@arch-btw ~> lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0 465,8G  0 disk 
├─sda1        8:1    0 196,9G  0 part /home
├─sda2        8:2    0 248,1G  0 part 
└─sda3        8:3    0  18,8G  0 part [SWAP]
sr0          11:0    1  1024M  0 rom  
nvme0n1     259:0    0 232,9G  0 disk 
├─nvme0n1p1 259:1    0     2G  0 part /mnt/gentoo/efi
│                                     /boot
├─nvme0n1p2 259:2    0   181G  0 part /mnt/gentoo
└─nvme0n1p3 259:3    0  49,9G  0 part /
```

Chroot:

```
root@arch-btw /h/i-use# chroot /mnt/gentoo /bin/bash
arch-btw / # fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@arch-btw /# mount /efi
root@arch-btw /# cd /usr/src/linux
root@arch-btw /u/s/linux# make install
  INSTALL /boot
Reading /usr/lib/kernel/install.conf...
/usr/lib/kernel/install.conf configures layout=efistub
/usr/lib/kernel/install.conf configures initrd_generator=none
/usr/lib/kernel/install.conf configures uki_generator=none

Running /usr/lib/kernel/postinst.d/95-efistub-uefi-mkconfig.install 6.8.5-gentoo-r1 /efi/EFI/Gentoo/vmlinuz-6.8.5-gentoo-r1.efi

 * Updating UEFI configuration
 * Running uefi-mkconfig...
 * Creating UEFI entry "0100" for "/efi/EFI/Linux/gentoo-6.7.9-gentoo.efi" found on "nvme0n1p1"...
 * No initramfs found for "/efi/EFI/Linux/gentoo-6.7.9-gentoo.efi".
 * Creating UEFI entry "0101" for "/efi/EFI/Linux/gentoo-6.7.9-gentoo-old.efi" found on "nvme0n1p1"...
 * No initramfs found for "/efi/EFI/Linux/gentoo-6.7.9-gentoo-old.efi".
 * Creating UEFI entry "0102" for "/efi/EFI/Gentoo/vmlinuz-6.8.5-gentoo-r1.efi" found on "nvme0n1p1"...
 * No initramfs found for "/efi/EFI/Gentoo/vmlinuz-6.8.5-gentoo-r1.efi".
 * Creating UEFI entry "0103" for "/efi/EFI/Gentoo/vmlinuz-6.8.5-gentoo-r1-old.efi" found on "nvme0n1p1"...
 * No initramfs found for "/efi/EFI/Gentoo/vmlinuz-6.8.5-gentoo-r1-old.efi".

```

EFI records:

```
i-use@arch-btw ~> efibootmgr -u
BootCurrent: 0001
Timeout: 1 seconds
BootOrder: 0103,0102,0101,0100,0000,0001,0018,0013,0014,0015,0016,0017,0019,001A
(...)
Boot0100* 6.7.9-gentoo	HD(1,GPT,5b0af188-1674-2d48-a16e-bc5e83b17d8a,0x800,0x400000)/\EFI\Linux\gentoo-6.7.9-gentoo.efi root=/dev/nvme0n1p3 rw
Boot0101* 6.7.9-gentoo-old	HD(1,GPT,5b0af188-1674-2d48-a16e-bc5e83b17d8a,0x800,0x400000)/\EFI\Linux\gentoo-6.7.9-gentoo-old.efi root=/dev/nvme0n1p3 rw
Boot0102* 6.8.5-gentoo-r1	HD(1,GPT,5b0af188-1674-2d48-a16e-bc5e83b17d8a,0x800,0x400000)/\EFI\Gentoo\vmlinuz-6.8.5-gentoo-r1.efi root=/dev/nvme0n1p3 rw
Boot0103* 6.8.5-gentoo-r1-old	HD(1,GPT,5b0af188-1674-2d48-a16e-bc5e83b17d8a,0x800,0x400000)/\EFI\Gentoo\vmlinuz-6.8.5-gentoo-r1-old.efi root=/dev/nvme0n1p3 rw
```

Expected behavior: records should have root=/dev/nvme0n1p2 instead
</details>

**Comment by AndrewAmmerlaan** [comment]
This is an issue for `sys-boot/uefi-mkconfig`.

@Biosias could you take a look here?

**Comment by AndrewAmmerlaan** [comment]
Actually, looking at the code, `uefi-mkconfig` does not determine `root=` or any other kernel cmdline. It reads it from config file or `/proc/cmdline`. Therefore, I suspect that the reason you find the wrong `root=` is because this is the `root=` present in `/proc/cmdline`.

Solution would be to set a proper cmdline in the `uefi-mkconfig` config file as described in the `README.md`: https://github.com/Biosias/uefi-mkconfig

**Comment by SpomJ** [comment]
> Solution would be to set a proper cmdline in the `uefi-mkconfig` config file as described in the `README.md`: https://github.com/Biosias/uefi-mkconfig

but still, maybe have it default to something like `findmnt / -no SOURCE` output, just for the ease of use sake

**Comment by AndrewAmmerlaan** [comment]
Or maybe it should not consider `/proc/cmdline` at all? 

I don't think it should add `root=` by itself always, perhaps what we need is to check if `root=` is included in the cmdline that we are going to set. And if so, check if this `root=` makes sense for the current system configuration.

**Comment by SpomJ** [comment]
> Or maybe it should not consider `/proc/cmdline` at all?
> 
> I don't think it should add `root=` by itself always, perhaps what we need is to check if `root=` is included in the cmdline that we are going to set. And if so, check if this `root=` makes sense for the current system configuration.

I mean, `/proc/cmdline` kinda makes sense for systems that are already running (though you have to do it for the first time anyways, so the config appearing is inevitable and this is basically useless). Also, when would root not be set?

**Comment by AndrewAmmerlaan** [comment]
> Also, when would root not be set?

There are several possible scenarios where you do not need to specify root= in your boot entry:
- Unified Kernel Images include their own built-in cmdline section
- You can build the cmdline or location of root into your kernel via the kernel config
- A dracut initramfs can append the proper root= to the cmdline at boot
- Systemd can dynamically detect the proper root partition in the initramfs stage at boot

And possibly there are even more methods of telling the kernel about your root partition that I don't know about.

**Comment by Biosias** [comment]
Also, uefi-mkconfig is in its early life. I'm very open to and will appreciate any suggestions or feedback!

**Comment by AndrewAmmerlaan** [comment]
> I've introduce warning in the new version that commands from /proc/cmdline are used. And will also mention in the documentation that if uefi-mkconfig uses /proc/cmdline , it should be considered a soft error.

I think with these changes, now in `::gentoo`, this can be closed.
